// Auto-generated mappers for AiContentJobs
// Generated at: 2025-10-06T21:02:35.491Z
// This file is automatically generated - do not edit manually

import type { aiContentJobs } from '@/lib/database';

// Drizzle inferred types
type AiContentJobsSelect = typeof aiContentJobs.$inferSelect;
type AiContentJobsInsert = typeof aiContentJobs.$inferInsert;
type AiContentJobsUpdate = typeof aiContentJobs.$inferInsert;
import type {
  AiContentJobCreate,
  AiContentJobUpdate,
  AiContentJobResponse,
} from '@/lib/contracts';

// Transform AiContentJobCreate to AiContentJobsInsert
export function fromCreateAicontentjobsDTO(input: AiContentJobCreate): AiContentJobsInsert {
  return {
    // TODO: Map Create fields to Insert fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: input.fieldName,
  };
}

// Transform AiContentJobUpdate to AiContentJobsUpdate with id
export function fromUpdateAicontentjobsDTO(input: AiContentJobUpdate): { id: string; changes: AiContentJobsUpdate } {
  const { id, ...changes } = input;
  return {
    id: id!,
    changes: {
      // TODO: Map Update fields to Update fields based on schema
      // This needs to be customized per entity based on the actual schema
      // Example: fieldName: changes.fieldName,
    }
  };
}

// Transform AiContentJobsSelect to AiContentJobResponse
export function toAicontentjobsDTO(row: AiContentJobsSelect): AiContentJobResponse {
  return {
    // TODO: Map Select fields to Response fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: row.fieldName,
    // createdAt: normalizeDate(row.createdAt),
    // updatedAt: normalizeDate(row.updatedAt),
  };
}

// Helper function to normalize dates to ISO strings
function normalizeDate(date: Date | null | undefined): string | null {
  if (!date) return null;
  return date.toISOString();
}

// Helper function to normalize jsonb fields
function normalizeJsonb<T>(value: T | null | undefined): T | null {
  return value || null;
}
