// Auto-generated mappers for AiConversations
// Generated at: 2025-10-06T21:02:35.491Z
// This file is automatically generated - do not edit manually

import type { aiConversations } from '@/lib/database';

// Drizzle inferred types
type AiConversationsSelect = typeof aiConversations.$inferSelect;
type AiConversationsInsert = typeof aiConversations.$inferInsert;
type AiConversationsUpdate = typeof aiConversations.$inferInsert;
import type {
  AiConversationCreate,
  AiConversationUpdate,
  AiConversationResponse,
} from '@/lib/contracts';

// Transform AiConversationCreate to AiConversationsInsert
export function fromCreateAiconversationsDTO(input: AiConversationCreate): AiConversationsInsert {
  return {
    // TODO: Map Create fields to Insert fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: input.fieldName,
  };
}

// Transform AiConversationUpdate to AiConversationsUpdate with id
export function fromUpdateAiconversationsDTO(input: AiConversationUpdate): { id: string; changes: AiConversationsUpdate } {
  const { id, ...changes } = input;
  return {
    id: id!,
    changes: {
      // TODO: Map Update fields to Update fields based on schema
      // This needs to be customized per entity based on the actual schema
      // Example: fieldName: changes.fieldName,
    }
  };
}

// Transform AiConversationsSelect to AiConversationResponse
export function toAiconversationsDTO(row: AiConversationsSelect): AiConversationResponse {
  return {
    // TODO: Map Select fields to Response fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: row.fieldName,
    // createdAt: normalizeDate(row.createdAt),
    // updatedAt: normalizeDate(row.updatedAt),
  };
}

// Helper function to normalize dates to ISO strings
function normalizeDate(date: Date | null | undefined): string | null {
  if (!date) return null;
  return date.toISOString();
}

// Helper function to normalize jsonb fields
function normalizeJsonb<T>(value: T | null | undefined): T | null {
  return value || null;
}
