// Auto-generated mappers for AiMessages
// Generated at: 2025-10-06T21:02:35.491Z
// This file is automatically generated - do not edit manually

import type { aiMessages } from '@/lib/database';

// Drizzle inferred types
type AiMessagesSelect = typeof aiMessages.$inferSelect;
type AiMessagesInsert = typeof aiMessages.$inferInsert;
type AiMessagesUpdate = typeof aiMessages.$inferInsert;
import type {
  AiMessageCreate,
  AiMessageUpdate,
  AiMessageResponse,
} from '@/lib/contracts';

// Transform AiMessageCreate to AiMessagesInsert
export function fromCreateAimessagesDTO(input: AiMessageCreate): AiMessagesInsert {
  return {
    // TODO: Map Create fields to Insert fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: input.fieldName,
  };
}

// Transform AiMessageUpdate to AiMessagesUpdate with id
export function fromUpdateAimessagesDTO(input: AiMessageUpdate): { id: string; changes: AiMessagesUpdate } {
  const { id, ...changes } = input;
  return {
    id: id!,
    changes: {
      // TODO: Map Update fields to Update fields based on schema
      // This needs to be customized per entity based on the actual schema
      // Example: fieldName: changes.fieldName,
    }
  };
}

// Transform AiMessagesSelect to AiMessageResponse
export function toAimessagesDTO(row: AiMessagesSelect): AiMessageResponse {
  return {
    // TODO: Map Select fields to Response fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: row.fieldName,
    // createdAt: normalizeDate(row.createdAt),
    // updatedAt: normalizeDate(row.updatedAt),
  };
}

// Helper function to normalize dates to ISO strings
function normalizeDate(date: Date | null | undefined): string | null {
  if (!date) return null;
  return date.toISOString();
}

// Helper function to normalize jsonb fields
function normalizeJsonb<T>(value: T | null | undefined): T | null {
  return value || null;
}
