// Auto-generated mappers for ApiKeys
// Generated at: 2025-10-06T21:02:35.492Z
// This file is automatically generated - do not edit manually

import type { apiKeys } from '@/lib/database';

// Drizzle inferred types
type ApiKeysSelect = typeof apiKeys.$inferSelect;
type ApiKeysInsert = typeof apiKeys.$inferInsert;
type ApiKeysUpdate = typeof apiKeys.$inferInsert;
import type {
  ApiKeyCreate,
  ApiKeyUpdate,
  ApiKeyResponse,
} from '@/lib/contracts';

// Transform ApiKeyCreate to ApiKeysInsert
export function fromCreateApikeysDTO(input: ApiKeyCreate): ApiKeysInsert {
  return {
    // TODO: Map Create fields to Insert fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: input.fieldName,
  };
}

// Transform ApiKeyUpdate to ApiKeysUpdate with id
export function fromUpdateApikeysDTO(input: ApiKeyUpdate): { id: string; changes: ApiKeysUpdate } {
  const { id, ...changes } = input;
  return {
    id: id!,
    changes: {
      // TODO: Map Update fields to Update fields based on schema
      // This needs to be customized per entity based on the actual schema
      // Example: fieldName: changes.fieldName,
    }
  };
}

// Transform ApiKeysSelect to ApiKeyResponse
export function toApikeysDTO(row: ApiKeysSelect): ApiKeyResponse {
  return {
    // TODO: Map Select fields to Response fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: row.fieldName,
    // createdAt: normalizeDate(row.createdAt),
    // updatedAt: normalizeDate(row.updatedAt),
  };
}

// Helper function to normalize dates to ISO strings
function normalizeDate(date: Date | null | undefined): string | null {
  if (!date) return null;
  return date.toISOString();
}

// Helper function to normalize jsonb fields
function normalizeJsonb<T>(value: T | null | undefined): T | null {
  return value || null;
}
