// Auto-generated mappers for AssessmentResponses
// Generated at: 2025-10-06T21:02:35.490Z
// This file is automatically generated - do not edit manually

import type { assessmentResponses } from '@/lib/database';

// Drizzle inferred types
type AssessmentResponsesSelect = typeof assessmentResponses.$inferSelect;
type AssessmentResponsesInsert = typeof assessmentResponses.$inferInsert;
type AssessmentResponsesUpdate = typeof assessmentResponses.$inferInsert;
import type {
  AssessmentResponseCreate,
  AssessmentResponseUpdate,
  AssessmentResponseResponse,
} from '@/lib/contracts';

// Transform AssessmentResponseCreate to AssessmentResponsesInsert
export function fromCreateAssessmentresponsesDTO(input: AssessmentResponseCreate): AssessmentResponsesInsert {
  return {
    // TODO: Map Create fields to Insert fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: input.fieldName,
  };
}

// Transform AssessmentResponseUpdate to AssessmentResponsesUpdate with id
export function fromUpdateAssessmentresponsesDTO(input: AssessmentResponseUpdate): { id: string; changes: AssessmentResponsesUpdate } {
  const { id, ...changes } = input;
  return {
    id: id!,
    changes: {
      // TODO: Map Update fields to Update fields based on schema
      // This needs to be customized per entity based on the actual schema
      // Example: fieldName: changes.fieldName,
    }
  };
}

// Transform AssessmentResponsesSelect to AssessmentResponseResponse
export function toAssessmentresponsesDTO(row: AssessmentResponsesSelect): AssessmentResponseResponse {
  return {
    // TODO: Map Select fields to Response fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: row.fieldName,
    // createdAt: normalizeDate(row.createdAt),
    // updatedAt: normalizeDate(row.updatedAt),
  };
}

// Helper function to normalize dates to ISO strings
function normalizeDate(date: Date | null | undefined): string | null {
  if (!date) return null;
  return date.toISOString();
}

// Helper function to normalize jsonb fields
function normalizeJsonb<T>(value: T | null | undefined): T | null {
  return value || null;
}
