// Auto-generated mappers for AuditLogs
// Generated at: 2025-10-06T21:02:35.492Z
// This file is automatically generated - do not edit manually

import type { auditLogs } from '@/lib/database';

// Drizzle inferred types
type AuditLogsSelect = typeof auditLogs.$inferSelect;
type AuditLogsInsert = typeof auditLogs.$inferInsert;
type AuditLogsUpdate = typeof auditLogs.$inferInsert;
import type {
  AuditLogCreate,
  AuditLogUpdate,
  AuditLogResponse,
} from '@/lib/contracts';

// Transform AuditLogCreate to AuditLogsInsert
export function fromCreateAuditlogsDTO(input: AuditLogCreate): AuditLogsInsert {
  return {
    // TODO: Map Create fields to Insert fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: input.fieldName,
  };
}

// Transform AuditLogUpdate to AuditLogsUpdate with id
export function fromUpdateAuditlogsDTO(input: AuditLogUpdate): { id: string; changes: AuditLogsUpdate } {
  const { id, ...changes } = input;
  return {
    id: id!,
    changes: {
      // TODO: Map Update fields to Update fields based on schema
      // This needs to be customized per entity based on the actual schema
      // Example: fieldName: changes.fieldName,
    }
  };
}

// Transform AuditLogsSelect to AuditLogResponse
export function toAuditlogsDTO(row: AuditLogsSelect): AuditLogResponse {
  return {
    // TODO: Map Select fields to Response fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: row.fieldName,
    // createdAt: normalizeDate(row.createdAt),
    // updatedAt: normalizeDate(row.updatedAt),
  };
}

// Helper function to normalize dates to ISO strings
function normalizeDate(date: Date | null | undefined): string | null {
  if (!date) return null;
  return date.toISOString();
}

// Helper function to normalize jsonb fields
function normalizeJsonb<T>(value: T | null | undefined): T | null {
  return value || null;
}
