// Auto-generated mappers for Collaborations
// Generated at: 2025-10-06T21:02:35.491Z
// This file is automatically generated - do not edit manually

import type { collaborations } from '@/lib/database';

// Drizzle inferred types
type CollaborationsSelect = typeof collaborations.$inferSelect;
type CollaborationsInsert = typeof collaborations.$inferInsert;
type CollaborationsUpdate = typeof collaborations.$inferInsert;
import type {
  CollaborationCreate,
  CollaborationUpdate,
  CollaborationResponse,
} from '@/lib/contracts';

// Transform CollaborationCreate to CollaborationsInsert
export function fromCreateCollaborationsDTO(input: CollaborationCreate): CollaborationsInsert {
  return {
    // TODO: Map Create fields to Insert fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: input.fieldName,
  };
}

// Transform CollaborationUpdate to CollaborationsUpdate with id
export function fromUpdateCollaborationsDTO(input: CollaborationUpdate): { id: string; changes: CollaborationsUpdate } {
  const { id, ...changes } = input;
  return {
    id: id!,
    changes: {
      // TODO: Map Update fields to Update fields based on schema
      // This needs to be customized per entity based on the actual schema
      // Example: fieldName: changes.fieldName,
    }
  };
}

// Transform CollaborationsSelect to CollaborationResponse
export function toCollaborationsDTO(row: CollaborationsSelect): CollaborationResponse {
  return {
    // TODO: Map Select fields to Response fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: row.fieldName,
    // createdAt: normalizeDate(row.createdAt),
    // updatedAt: normalizeDate(row.updatedAt),
  };
}

// Helper function to normalize dates to ISO strings
function normalizeDate(date: Date | null | undefined): string | null {
  if (!date) return null;
  return date.toISOString();
}

// Helper function to normalize jsonb fields
function normalizeJsonb<T>(value: T | null | undefined): T | null {
  return value || null;
}
