// Auto-generated mappers for Communities
// Generated at: 2025-10-06T21:02:35.491Z
// This file is automatically generated - do not edit manually

import type { communities } from '@/lib/database';

// Drizzle inferred types
type CommunitiesSelect = typeof communities.$inferSelect;
type CommunitiesInsert = typeof communities.$inferInsert;
type CommunitiesUpdate = typeof communities.$inferInsert;
import type {
  CommunityCreate,
  CommunityUpdate,
  CommunityResponse,
} from '@/lib/contracts';

// Transform CommunityCreate to CommunitiesInsert
export function fromCreateCommunitiesDTO(input: CommunityCreate): CommunitiesInsert {
  return {
    // TODO: Map Create fields to Insert fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: input.fieldName,
  };
}

// Transform CommunityUpdate to CommunitiesUpdate with id
export function fromUpdateCommunitiesDTO(input: CommunityUpdate): { id: string; changes: CommunitiesUpdate } {
  const { id, ...changes } = input;
  return {
    id: id!,
    changes: {
      // TODO: Map Update fields to Update fields based on schema
      // This needs to be customized per entity based on the actual schema
      // Example: fieldName: changes.fieldName,
    }
  };
}

// Transform CommunitiesSelect to CommunityResponse
export function toCommunitiesDTO(row: CommunitiesSelect): CommunityResponse {
  return {
    // TODO: Map Select fields to Response fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: row.fieldName,
    // createdAt: normalizeDate(row.createdAt),
    // updatedAt: normalizeDate(row.updatedAt),
  };
}

// Helper function to normalize dates to ISO strings
function normalizeDate(date: Date | null | undefined): string | null {
  if (!date) return null;
  return date.toISOString();
}

// Helper function to normalize jsonb fields
function normalizeJsonb<T>(value: T | null | undefined): T | null {
  return value || null;
}
