// Auto-generated mappers for CommunityPostVotes
// Generated at: 2025-10-06T21:02:35.491Z
// This file is automatically generated - do not edit manually

import type { communityPostVotes } from '@/lib/database';

// Drizzle inferred types
type CommunityPostVotesSelect = typeof communityPostVotes.$inferSelect;
type CommunityPostVotesInsert = typeof communityPostVotes.$inferInsert;
type CommunityPostVotesUpdate = typeof communityPostVotes.$inferInsert;
import type {
  CommunityPostVoteCreate,
  CommunityPostVoteUpdate,
  CommunityPostVoteResponse,
} from '@/lib/contracts';

// Transform CommunityPostVoteCreate to CommunityPostVotesInsert
export function fromCreateCommunitypostvotesDTO(input: CommunityPostVoteCreate): CommunityPostVotesInsert {
  return {
    // TODO: Map Create fields to Insert fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: input.fieldName,
  };
}

// Transform CommunityPostVoteUpdate to CommunityPostVotesUpdate with id
export function fromUpdateCommunitypostvotesDTO(input: CommunityPostVoteUpdate): { id: string; changes: CommunityPostVotesUpdate } {
  const { id, ...changes } = input;
  return {
    id: id!,
    changes: {
      // TODO: Map Update fields to Update fields based on schema
      // This needs to be customized per entity based on the actual schema
      // Example: fieldName: changes.fieldName,
    }
  };
}

// Transform CommunityPostVotesSelect to CommunityPostVoteResponse
export function toCommunitypostvotesDTO(row: CommunityPostVotesSelect): CommunityPostVoteResponse {
  return {
    // TODO: Map Select fields to Response fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: row.fieldName,
    // createdAt: normalizeDate(row.createdAt),
    // updatedAt: normalizeDate(row.updatedAt),
  };
}

// Helper function to normalize dates to ISO strings
function normalizeDate(date: Date | null | undefined): string | null {
  if (!date) return null;
  return date.toISOString();
}

// Helper function to normalize jsonb fields
function normalizeJsonb<T>(value: T | null | undefined): T | null {
  return value || null;
}
