// Auto-generated mappers for Coupons
// Generated at: 2025-10-06T21:02:35.492Z
// This file is automatically generated - do not edit manually

import type { coupons } from '@/lib/database';

// Drizzle inferred types
type CouponsSelect = typeof coupons.$inferSelect;
type CouponsInsert = typeof coupons.$inferInsert;
type CouponsUpdate = typeof coupons.$inferInsert;
import type {
  CouponCreate,
  CouponUpdate,
  CouponResponse,
} from '@/lib/contracts';

// Transform CouponCreate to CouponsInsert
export function fromCreateCouponsDTO(input: CouponCreate): CouponsInsert {
  return {
    // TODO: Map Create fields to Insert fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: input.fieldName,
  };
}

// Transform CouponUpdate to CouponsUpdate with id
export function fromUpdateCouponsDTO(input: CouponUpdate): { id: string; changes: CouponsUpdate } {
  const { id, ...changes } = input;
  return {
    id: id!,
    changes: {
      // TODO: Map Update fields to Update fields based on schema
      // This needs to be customized per entity based on the actual schema
      // Example: fieldName: changes.fieldName,
    }
  };
}

// Transform CouponsSelect to CouponResponse
export function toCouponsDTO(row: CouponsSelect): CouponResponse {
  return {
    // TODO: Map Select fields to Response fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: row.fieldName,
    // createdAt: normalizeDate(row.createdAt),
    // updatedAt: normalizeDate(row.updatedAt),
  };
}

// Helper function to normalize dates to ISO strings
function normalizeDate(date: Date | null | undefined): string | null {
  if (!date) return null;
  return date.toISOString();
}

// Helper function to normalize jsonb fields
function normalizeJsonb<T>(value: T | null | undefined): T | null {
  return value || null;
}
