// Auto-generated mappers for LearningOutcomes
// Generated at: 2025-10-06T21:02:35.492Z
// This file is automatically generated - do not edit manually

import type { learningOutcomes } from '@/lib/database';

// Drizzle inferred types
type LearningOutcomesSelect = typeof learningOutcomes.$inferSelect;
type LearningOutcomesInsert = typeof learningOutcomes.$inferInsert;
type LearningOutcomesUpdate = typeof learningOutcomes.$inferInsert;
import type {
  LearningOutcomeCreate,
  LearningOutcomeUpdate,
  LearningOutcomeResponse,
} from '@/lib/contracts';

// Transform LearningOutcomeCreate to LearningOutcomesInsert
export function fromCreateLearningoutcomesDTO(input: LearningOutcomeCreate): LearningOutcomesInsert {
  return {
    // TODO: Map Create fields to Insert fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: input.fieldName,
  };
}

// Transform LearningOutcomeUpdate to LearningOutcomesUpdate with id
export function fromUpdateLearningoutcomesDTO(input: LearningOutcomeUpdate): { id: string; changes: LearningOutcomesUpdate } {
  const { id, ...changes } = input;
  return {
    id: id!,
    changes: {
      // TODO: Map Update fields to Update fields based on schema
      // This needs to be customized per entity based on the actual schema
      // Example: fieldName: changes.fieldName,
    }
  };
}

// Transform LearningOutcomesSelect to LearningOutcomeResponse
export function toLearningoutcomesDTO(row: LearningOutcomesSelect): LearningOutcomeResponse {
  return {
    // TODO: Map Select fields to Response fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: row.fieldName,
    // createdAt: normalizeDate(row.createdAt),
    // updatedAt: normalizeDate(row.updatedAt),
  };
}

// Helper function to normalize dates to ISO strings
function normalizeDate(date: Date | null | undefined): string | null {
  if (!date) return null;
  return date.toISOString();
}

// Helper function to normalize jsonb fields
function normalizeJsonb<T>(value: T | null | undefined): T | null {
  return value || null;
}
