// Auto-generated mappers for MovementMetrics
// Generated at: 2025-10-06T21:02:35.492Z
// This file is automatically generated - do not edit manually

import type { movementMetrics } from '@/lib/database';

// Drizzle inferred types
type MovementMetricsSelect = typeof movementMetrics.$inferSelect;
type MovementMetricsInsert = typeof movementMetrics.$inferInsert;
type MovementMetricsUpdate = typeof movementMetrics.$inferInsert;
import type {
  MovementMetricCreate,
  MovementMetricUpdate,
  MovementMetricResponse,
} from '@/lib/contracts';

// Transform MovementMetricCreate to MovementMetricsInsert
export function fromCreateMovementmetricsDTO(input: MovementMetricCreate): MovementMetricsInsert {
  return {
    // TODO: Map Create fields to Insert fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: input.fieldName,
  };
}

// Transform MovementMetricUpdate to MovementMetricsUpdate with id
export function fromUpdateMovementmetricsDTO(input: MovementMetricUpdate): { id: string; changes: MovementMetricsUpdate } {
  const { id, ...changes } = input;
  return {
    id: id!,
    changes: {
      // TODO: Map Update fields to Update fields based on schema
      // This needs to be customized per entity based on the actual schema
      // Example: fieldName: changes.fieldName,
    }
  };
}

// Transform MovementMetricsSelect to MovementMetricResponse
export function toMovementmetricsDTO(row: MovementMetricsSelect): MovementMetricResponse {
  return {
    // TODO: Map Select fields to Response fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: row.fieldName,
    // createdAt: normalizeDate(row.createdAt),
    // updatedAt: normalizeDate(row.updatedAt),
  };
}

// Helper function to normalize dates to ISO strings
function normalizeDate(date: Date | null | undefined): string | null {
  if (!date) return null;
  return date.toISOString();
}

// Helper function to normalize jsonb fields
function normalizeJsonb<T>(value: T | null | undefined): T | null {
  return value || null;
}
