// Auto-generated mappers for OrganizationMemberships
// Generated at: 2025-10-06T21:02:35.489Z
// This file is automatically generated - do not edit manually

import type { organizationMemberships } from '@/lib/database';

// Drizzle inferred types
type OrganizationMembershipsSelect = typeof organizationMemberships.$inferSelect;
type OrganizationMembershipsInsert = typeof organizationMemberships.$inferInsert;
type OrganizationMembershipsUpdate = typeof organizationMemberships.$inferInsert;
import type {
  OrganizationMembershipCreate,
  OrganizationMembershipUpdate,
  OrganizationMembershipResponse,
} from '@/lib/contracts';

// Transform OrganizationMembershipCreate to OrganizationMembershipsInsert
export function fromCreateOrganizationmembershipsDTO(input: OrganizationMembershipCreate): OrganizationMembershipsInsert {
  return {
    // TODO: Map Create fields to Insert fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: input.fieldName,
  };
}

// Transform OrganizationMembershipUpdate to OrganizationMembershipsUpdate with id
export function fromUpdateOrganizationmembershipsDTO(input: OrganizationMembershipUpdate): { id: string; changes: OrganizationMembershipsUpdate } {
  const { id, ...changes } = input;
  return {
    id: id!,
    changes: {
      // TODO: Map Update fields to Update fields based on schema
      // This needs to be customized per entity based on the actual schema
      // Example: fieldName: changes.fieldName,
    }
  };
}

// Transform OrganizationMembershipsSelect to OrganizationMembershipResponse
export function toOrganizationmembershipsDTO(row: OrganizationMembershipsSelect): OrganizationMembershipResponse {
  return {
    // TODO: Map Select fields to Response fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: row.fieldName,
    // createdAt: normalizeDate(row.createdAt),
    // updatedAt: normalizeDate(row.updatedAt),
  };
}

// Helper function to normalize dates to ISO strings
function normalizeDate(date: Date | null | undefined): string | null {
  if (!date) return null;
  return date.toISOString();
}

// Helper function to normalize jsonb fields
function normalizeJsonb<T>(value: T | null | undefined): T | null {
  return value || null;
}
