// Auto-generated mappers for SeriesContentItems
// Generated at: 2025-10-06T21:02:35.491Z
// This file is automatically generated - do not edit manually

import type { seriesContentItems } from '@/lib/database';

// Drizzle inferred types
type SeriesContentItemsSelect = typeof seriesContentItems.$inferSelect;
type SeriesContentItemsInsert = typeof seriesContentItems.$inferInsert;
type SeriesContentItemsUpdate = typeof seriesContentItems.$inferInsert;
import type {
  SeriesContentItemCreate,
  SeriesContentItemUpdate,
  SeriesContentItemResponse,
} from '@/lib/contracts';

// Transform SeriesContentItemCreate to SeriesContentItemsInsert
export function fromCreateSeriescontentitemsDTO(input: SeriesContentItemCreate): SeriesContentItemsInsert {
  return {
    // TODO: Map Create fields to Insert fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: input.fieldName,
  };
}

// Transform SeriesContentItemUpdate to SeriesContentItemsUpdate with id
export function fromUpdateSeriescontentitemsDTO(input: SeriesContentItemUpdate): { id: string; changes: SeriesContentItemsUpdate } {
  const { id, ...changes } = input;
  return {
    id: id!,
    changes: {
      // TODO: Map Update fields to Update fields based on schema
      // This needs to be customized per entity based on the actual schema
      // Example: fieldName: changes.fieldName,
    }
  };
}

// Transform SeriesContentItemsSelect to SeriesContentItemResponse
export function toSeriescontentitemsDTO(row: SeriesContentItemsSelect): SeriesContentItemResponse {
  return {
    // TODO: Map Select fields to Response fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: row.fieldName,
    // createdAt: normalizeDate(row.createdAt),
    // updatedAt: normalizeDate(row.updatedAt),
  };
}

// Helper function to normalize dates to ISO strings
function normalizeDate(date: Date | null | undefined): string | null {
  if (!date) return null;
  return date.toISOString();
}

// Helper function to normalize jsonb fields
function normalizeJsonb<T>(value: T | null | undefined): T | null {
  return value || null;
}
