// Auto-generated mappers for TheologicalConcepts
// Generated at: 2025-10-06T21:02:35.491Z
// This file is automatically generated - do not edit manually

import type { theologicalConcepts } from '@/lib/database';

// Drizzle inferred types
type TheologicalConceptsSelect = typeof theologicalConcepts.$inferSelect;
type TheologicalConceptsInsert = typeof theologicalConcepts.$inferInsert;
type TheologicalConceptsUpdate = typeof theologicalConcepts.$inferInsert;
import type {
  TheologicalConceptCreate,
  TheologicalConceptUpdate,
  TheologicalConceptResponse,
} from '@/lib/contracts';

// Transform TheologicalConceptCreate to TheologicalConceptsInsert
export function fromCreateTheologicalconceptsDTO(input: TheologicalConceptCreate): TheologicalConceptsInsert {
  return {
    // TODO: Map Create fields to Insert fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: input.fieldName,
  };
}

// Transform TheologicalConceptUpdate to TheologicalConceptsUpdate with id
export function fromUpdateTheologicalconceptsDTO(input: TheologicalConceptUpdate): { id: string; changes: TheologicalConceptsUpdate } {
  const { id, ...changes } = input;
  return {
    id: id!,
    changes: {
      // TODO: Map Update fields to Update fields based on schema
      // This needs to be customized per entity based on the actual schema
      // Example: fieldName: changes.fieldName,
    }
  };
}

// Transform TheologicalConceptsSelect to TheologicalConceptResponse
export function toTheologicalconceptsDTO(row: TheologicalConceptsSelect): TheologicalConceptResponse {
  return {
    // TODO: Map Select fields to Response fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: row.fieldName,
    // createdAt: normalizeDate(row.createdAt),
    // updatedAt: normalizeDate(row.updatedAt),
  };
}

// Helper function to normalize dates to ISO strings
function normalizeDate(date: Date | null | undefined): string | null {
  if (!date) return null;
  return date.toISOString();
}

// Helper function to normalize jsonb fields
function normalizeJsonb<T>(value: T | null | undefined): T | null {
  return value || null;
}
