// Auto-generated mappers for Transactions
// Generated at: 2025-10-06T21:02:35.492Z
// This file is automatically generated - do not edit manually

import type { transactions } from '@/lib/database';

// Drizzle inferred types
type TransactionsSelect = typeof transactions.$inferSelect;
type TransactionsInsert = typeof transactions.$inferInsert;
type TransactionsUpdate = typeof transactions.$inferInsert;
import type {
  TransactionCreate,
  TransactionUpdate,
  TransactionResponse,
} from '@/lib/contracts';

// Transform TransactionCreate to TransactionsInsert
export function fromCreateTransactionsDTO(input: TransactionCreate): TransactionsInsert {
  return {
    // TODO: Map Create fields to Insert fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: input.fieldName,
  };
}

// Transform TransactionUpdate to TransactionsUpdate with id
export function fromUpdateTransactionsDTO(input: TransactionUpdate): { id: string; changes: TransactionsUpdate } {
  const { id, ...changes } = input;
  return {
    id: id!,
    changes: {
      // TODO: Map Update fields to Update fields based on schema
      // This needs to be customized per entity based on the actual schema
      // Example: fieldName: changes.fieldName,
    }
  };
}

// Transform TransactionsSelect to TransactionResponse
export function toTransactionsDTO(row: TransactionsSelect): TransactionResponse {
  return {
    // TODO: Map Select fields to Response fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: row.fieldName,
    // createdAt: normalizeDate(row.createdAt),
    // updatedAt: normalizeDate(row.updatedAt),
  };
}

// Helper function to normalize dates to ISO strings
function normalizeDate(date: Date | null | undefined): string | null {
  if (!date) return null;
  return date.toISOString();
}

// Helper function to normalize jsonb fields
function normalizeJsonb<T>(value: T | null | undefined): T | null {
  return value || null;
}
