// Auto-generated mappers for UserContentInteractions
// Generated at: 2025-10-06T21:02:35.492Z
// This file is automatically generated - do not edit manually

import type { userContentInteractions } from '@/lib/database';

// Drizzle inferred types
type UserContentInteractionsSelect = typeof userContentInteractions.$inferSelect;
type UserContentInteractionsInsert = typeof userContentInteractions.$inferInsert;
type UserContentInteractionsUpdate = typeof userContentInteractions.$inferInsert;
import type {
  UserContentInteractionCreate,
  UserContentInteractionUpdate,
  UserContentInteractionResponse,
} from '@/lib/contracts';

// Transform UserContentInteractionCreate to UserContentInteractionsInsert
export function fromCreateUsercontentinteractionsDTO(input: UserContentInteractionCreate): UserContentInteractionsInsert {
  return {
    // TODO: Map Create fields to Insert fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: input.fieldName,
  };
}

// Transform UserContentInteractionUpdate to UserContentInteractionsUpdate with id
export function fromUpdateUsercontentinteractionsDTO(input: UserContentInteractionUpdate): { id: string; changes: UserContentInteractionsUpdate } {
  const { id, ...changes } = input;
  return {
    id: id!,
    changes: {
      // TODO: Map Update fields to Update fields based on schema
      // This needs to be customized per entity based on the actual schema
      // Example: fieldName: changes.fieldName,
    }
  };
}

// Transform UserContentInteractionsSelect to UserContentInteractionResponse
export function toUsercontentinteractionsDTO(row: UserContentInteractionsSelect): UserContentInteractionResponse {
  return {
    // TODO: Map Select fields to Response fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: row.fieldName,
    // createdAt: normalizeDate(row.createdAt),
    // updatedAt: normalizeDate(row.updatedAt),
  };
}

// Helper function to normalize dates to ISO strings
function normalizeDate(date: Date | null | undefined): string | null {
  if (!date) return null;
  return date.toISOString();
}

// Helper function to normalize jsonb fields
function normalizeJsonb<T>(value: T | null | undefined): T | null {
  return value || null;
}
