// Auto-generated mappers for UserAnalyticsEvents
// Generated at: 2025-10-06T21:02:35.492Z
// This file is automatically generated - do not edit manually

import type { userAnalyticsEvents } from '@/lib/database';

// Drizzle inferred types
type UserAnalyticsEventsSelect = typeof userAnalyticsEvents.$inferSelect;
type UserAnalyticsEventsInsert = typeof userAnalyticsEvents.$inferInsert;
type UserAnalyticsEventsUpdate = typeof userAnalyticsEvents.$inferInsert;
import type {
  UserAnalyticsEventCreate,
  UserAnalyticsEventUpdate,
  UserAnalyticsEventResponse,
} from '@/lib/contracts';

// Transform UserAnalyticsEventCreate to UserAnalyticsEventsInsert
export function fromCreateUseranalyticseventsDTO(input: UserAnalyticsEventCreate): UserAnalyticsEventsInsert {
  return {
    // TODO: Map Create fields to Insert fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: input.fieldName,
  };
}

// Transform UserAnalyticsEventUpdate to UserAnalyticsEventsUpdate with id
export function fromUpdateUseranalyticseventsDTO(input: UserAnalyticsEventUpdate): { id: string; changes: UserAnalyticsEventsUpdate } {
  const { id, ...changes } = input;
  return {
    id: id!,
    changes: {
      // TODO: Map Update fields to Update fields based on schema
      // This needs to be customized per entity based on the actual schema
      // Example: fieldName: changes.fieldName,
    }
  };
}

// Transform UserAnalyticsEventsSelect to UserAnalyticsEventResponse
export function toUseranalyticseventsDTO(row: UserAnalyticsEventsSelect): UserAnalyticsEventResponse {
  return {
    // TODO: Map Select fields to Response fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: row.fieldName,
    // createdAt: normalizeDate(row.createdAt),
    // updatedAt: normalizeDate(row.updatedAt),
  };
}

// Helper function to normalize dates to ISO strings
function normalizeDate(date: Date | null | undefined): string | null {
  if (!date) return null;
  return date.toISOString();
}

// Helper function to normalize jsonb fields
function normalizeJsonb<T>(value: T | null | undefined): T | null {
  return value || null;
}
