// Auto-generated mappers for UserNotificationStatus
// Generated at: 2025-10-06T21:02:35.492Z
// This file is automatically generated - do not edit manually

import type { userNotificationStatus } from '@/lib/database';

// Drizzle inferred types
type UserNotificationStatusSelect = typeof userNotificationStatus.$inferSelect;
type UserNotificationStatusInsert = typeof userNotificationStatus.$inferInsert;
type UserNotificationStatusUpdate = typeof userNotificationStatus.$inferInsert;
import type {
  UserNotificationStatusCreate,
  UserNotificationStatusUpdate,
  UserNotificationStatusResponse,
} from '@/lib/contracts';

// Transform UserNotificationStatusCreate to UserNotificationStatusInsert
export function fromCreateUsernotificationstatusDTO(input: UserNotificationStatusCreate): UserNotificationStatusInsert {
  return {
    // TODO: Map Create fields to Insert fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: input.fieldName,
  };
}

// Transform UserNotificationStatusUpdate to UserNotificationStatusUpdate with id
export function fromUpdateUsernotificationstatusDTO(input: UserNotificationStatusUpdate): { id: string; changes: UserNotificationStatusUpdate } {
  const { id, ...changes } = input;
  return {
    id: id!,
    changes: {
      // TODO: Map Update fields to Update fields based on schema
      // This needs to be customized per entity based on the actual schema
      // Example: fieldName: changes.fieldName,
    }
  };
}

// Transform UserNotificationStatusSelect to UserNotificationStatusResponse
export function toUsernotificationstatusDTO(row: UserNotificationStatusSelect): UserNotificationStatusResponse {
  return {
    // TODO: Map Select fields to Response fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: row.fieldName,
    // createdAt: normalizeDate(row.createdAt),
    // updatedAt: normalizeDate(row.updatedAt),
  };
}

// Helper function to normalize dates to ISO strings
function normalizeDate(date: Date | null | undefined): string | null {
  if (!date) return null;
  return date.toISOString();
}

// Helper function to normalize jsonb fields
function normalizeJsonb<T>(value: T | null | undefined): T | null {
  return value || null;
}
