// Auto-generated mappers for UserConsents
// Generated at: 2025-10-06T21:02:35.492Z
// This file is automatically generated - do not edit manually

import type { userConsents } from '@/lib/database';

// Drizzle inferred types
type UserConsentsSelect = typeof userConsents.$inferSelect;
type UserConsentsInsert = typeof userConsents.$inferInsert;
type UserConsentsUpdate = typeof userConsents.$inferInsert;
import type {
  UserConsentCreate,
  UserConsentUpdate,
  UserConsentResponse,
} from '@/lib/contracts';

// Transform UserConsentCreate to UserConsentsInsert
export function fromCreateUserconsentsDTO(input: UserConsentCreate): UserConsentsInsert {
  return {
    // TODO: Map Create fields to Insert fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: input.fieldName,
  };
}

// Transform UserConsentUpdate to UserConsentsUpdate with id
export function fromUpdateUserconsentsDTO(input: UserConsentUpdate): { id: string; changes: UserConsentsUpdate } {
  const { id, ...changes } = input;
  return {
    id: id!,
    changes: {
      // TODO: Map Update fields to Update fields based on schema
      // This needs to be customized per entity based on the actual schema
      // Example: fieldName: changes.fieldName,
    }
  };
}

// Transform UserConsentsSelect to UserConsentResponse
export function toUserconsentsDTO(row: UserConsentsSelect): UserConsentResponse {
  return {
    // TODO: Map Select fields to Response fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: row.fieldName,
    // createdAt: normalizeDate(row.createdAt),
    // updatedAt: normalizeDate(row.updatedAt),
  };
}

// Helper function to normalize dates to ISO strings
function normalizeDate(date: Date | null | undefined): string | null {
  if (!date) return null;
  return date.toISOString();
}

// Helper function to normalize jsonb fields
function normalizeJsonb<T>(value: T | null | undefined): T | null {
  return value || null;
}
