// Auto-generated mappers for UserSubscriptions
// Generated at: 2025-10-06T21:02:35.492Z
// This file is automatically generated - do not edit manually

import type { userSubscriptions } from '@/lib/database';

// Drizzle inferred types
type UserSubscriptionsSelect = typeof userSubscriptions.$inferSelect;
type UserSubscriptionsInsert = typeof userSubscriptions.$inferInsert;
type UserSubscriptionsUpdate = typeof userSubscriptions.$inferInsert;
import type {
  UserSubscriptionCreate,
  UserSubscriptionUpdate,
  UserSubscriptionResponse,
} from '@/lib/contracts';

// Transform UserSubscriptionCreate to UserSubscriptionsInsert
export function fromCreateUsersubscriptionsDTO(input: UserSubscriptionCreate): UserSubscriptionsInsert {
  return {
    // TODO: Map Create fields to Insert fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: input.fieldName,
  };
}

// Transform UserSubscriptionUpdate to UserSubscriptionsUpdate with id
export function fromUpdateUsersubscriptionsDTO(input: UserSubscriptionUpdate): { id: string; changes: UserSubscriptionsUpdate } {
  const { id, ...changes } = input;
  return {
    id: id!,
    changes: {
      // TODO: Map Update fields to Update fields based on schema
      // This needs to be customized per entity based on the actual schema
      // Example: fieldName: changes.fieldName,
    }
  };
}

// Transform UserSubscriptionsSelect to UserSubscriptionResponse
export function toUsersubscriptionsDTO(row: UserSubscriptionsSelect): UserSubscriptionResponse {
  return {
    // TODO: Map Select fields to Response fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: row.fieldName,
    // createdAt: normalizeDate(row.createdAt),
    // updatedAt: normalizeDate(row.updatedAt),
  };
}

// Helper function to normalize dates to ISO strings
function normalizeDate(date: Date | null | undefined): string | null {
  if (!date) return null;
  return date.toISOString();
}

// Helper function to normalize jsonb fields
function normalizeJsonb<T>(value: T | null | undefined): T | null {
  return value || null;
}
