// Auto-generated mappers for UserFeatureFlags
// Generated at: 2025-10-06T21:02:35.492Z
// This file is automatically generated - do not edit manually

import type { userFeatureFlags } from '@/lib/database';

// Drizzle inferred types
type UserFeatureFlagsSelect = typeof userFeatureFlags.$inferSelect;
type UserFeatureFlagsInsert = typeof userFeatureFlags.$inferInsert;
type UserFeatureFlagsUpdate = typeof userFeatureFlags.$inferInsert;
import type {
  UserFeatureFlagCreate,
  UserFeatureFlagUpdate,
  UserFeatureFlagResponse,
} from '@/lib/contracts';

// Transform UserFeatureFlagCreate to UserFeatureFlagsInsert
export function fromCreateUserfeatureflagsDTO(input: UserFeatureFlagCreate): UserFeatureFlagsInsert {
  return {
    // TODO: Map Create fields to Insert fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: input.fieldName,
  };
}

// Transform UserFeatureFlagUpdate to UserFeatureFlagsUpdate with id
export function fromUpdateUserfeatureflagsDTO(input: UserFeatureFlagUpdate): { id: string; changes: UserFeatureFlagsUpdate } {
  const { id, ...changes } = input;
  return {
    id: id!,
    changes: {
      // TODO: Map Update fields to Update fields based on schema
      // This needs to be customized per entity based on the actual schema
      // Example: fieldName: changes.fieldName,
    }
  };
}

// Transform UserFeatureFlagsSelect to UserFeatureFlagResponse
export function toUserfeatureflagsDTO(row: UserFeatureFlagsSelect): UserFeatureFlagResponse {
  return {
    // TODO: Map Select fields to Response fields based on schema
    // This needs to be customized per entity based on the actual schema
    // Example: fieldName: row.fieldName,
    // createdAt: normalizeDate(row.createdAt),
    // updatedAt: normalizeDate(row.updatedAt),
  };
}

// Helper function to normalize dates to ISO strings
function normalizeDate(date: Date | null | undefined): string | null {
  if (!date) return null;
  return date.toISOString();
}

// Helper function to normalize jsonb fields
function normalizeJsonb<T>(value: T | null | undefined): T | null {
  return value || null;
}
