// Auto-generated types for database
// Generated at: 2025-10-06T20:26:00.000Z
// This file is automatically generated - do not edit manually

// UserProfiles types from auth.ts
export type UserProfilesSelect = {
  id: string;
  email: string;
  passwordHash: string | null;
  firstName: string;
  lastName: string;
  displayName: string | null;
  bio: string | null;
  avatarUrl: string | null;
  ministryRole:
    | 'senior_pastor'
    | 'associate_pastor'
    | 'church_planter'
    | 'denominational_leader'
    | 'seminary_professor'
    | 'seminary_student'
    | 'ministry_staff'
    | 'missionary'
    | 'marketplace_minister'
    | 'nonprofit_leader'
    | 'consultant'
    | 'academic_researcher'
    | 'emerging_leader'
    | 'other';
  denomination: string | null;
  organizationName: string | null;
  yearsInMinistry: number | null;
  countryCode: string | null;
  timezone: string | null;
  languagePrimary: string;
  culturalContext:
    | 'western'
    | 'eastern'
    | 'african'
    | 'latin_american'
    | 'middle_eastern'
    | 'oceanic'
    | 'mixed'
    | 'global'
    | null;
  assessmentMovementAlignment: number | null;
  assessmentAudienceEngagement: number | null;
  assessmentContentReadiness: number | null;
  assessmentRevenuePotential: number | null;
  assessmentNetworkEffects: number | null;
  assessmentStrategicFit: number | null;
  assessmentTotal: number | null;
  leaderTier: 'core' | 'network' | 'emerging' | 'community' | null;
  subdomain: string | null;
  customDomain: string | null;
  platformTitle: string | null;
  subscriptionTier:
    | 'free'
    | 'individual'
    | 'professional'
    | 'leader'
    | 'institutional';
  theologicalFocus: string[];
  brandColors: {
    primary: string;
    secondary: string;
    accent: string;
  };
  emailNotifications: {
    dailyDigest: boolean;
    collaborationRequests: boolean;
    revenueReports: boolean;
    communityUpdates: boolean;
  };
  privacySettings: {
    publicProfile: boolean;
    showAssessmentResults: boolean;
    allowNetworking: boolean;
    shareAnalytics: boolean;
  };
  onboardingCompleted: boolean;
  onboardingStep: number;
  accountStatus: 'active' | 'inactive' | 'suspended' | 'pending_verification';
  createdAt: Date;
  updatedAt: Date;
  lastActiveAt: Date;
};

export type UserProfilesInsert = {
  id: string;
  email: string;
  passwordHash?: string | null;
  firstName: string;
  lastName: string;
  displayName?: string | null;
  bio?: string | null;
  avatarUrl?: string | null;
  ministryRole:
    | 'senior_pastor'
    | 'associate_pastor'
    | 'church_planter'
    | 'denominational_leader'
    | 'seminary_professor'
    | 'seminary_student'
    | 'ministry_staff'
    | 'missionary'
    | 'marketplace_minister'
    | 'nonprofit_leader'
    | 'consultant'
    | 'academic_researcher'
    | 'emerging_leader'
    | 'other';
  denomination?: string | null;
  organizationName?: string | null;
  yearsInMinistry?: number | null;
  countryCode?: string | null;
  timezone?: string | null;
  languagePrimary?: string;
  culturalContext?:
    | 'western'
    | 'eastern'
    | 'african'
    | 'latin_american'
    | 'middle_eastern'
    | 'oceanic'
    | 'mixed'
    | 'global'
    | null;
  assessmentMovementAlignment?: number | null;
  assessmentAudienceEngagement?: number | null;
  assessmentContentReadiness?: number | null;
  assessmentRevenuePotential?: number | null;
  assessmentNetworkEffects?: number | null;
  assessmentStrategicFit?: number | null;
  assessmentTotal?: number | null;
  leaderTier?: 'core' | 'network' | 'emerging' | 'community' | null;
  subdomain?: string | null;
  customDomain?: string | null;
  platformTitle?: string | null;
  subscriptionTier?:
    | 'free'
    | 'individual'
    | 'professional'
    | 'leader'
    | 'institutional';
  theologicalFocus?: string[];
  brandColors?: {
    primary: string;
    secondary: string;
    accent: string;
  };
  emailNotifications?: {
    dailyDigest: boolean;
    collaborationRequests: boolean;
    revenueReports: boolean;
    communityUpdates: boolean;
  };
  privacySettings?: {
    publicProfile: boolean;
    showAssessmentResults: boolean;
    allowNetworking: boolean;
    shareAnalytics: boolean;
  };
  onboardingCompleted?: boolean;
  onboardingStep?: number;
  accountStatus?: 'active' | 'inactive' | 'suspended' | 'pending_verification';
  createdAt?: Date;
  updatedAt?: Date;
  lastActiveAt?: Date;
};

export type UserProfilesUpdate = Partial<UserProfilesInsert>;

// Organizations types from auth.ts
export type OrganizationsSelect = {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  website: string | null;
  logoUrl: string | null;
  organizationType:
    | 'church'
    | 'denomination'
    | 'seminary'
    | 'ministry_network'
    | 'nonprofit'
    | 'business'
    | 'other';
  sizeCategory: 'startup' | 'small' | 'medium' | 'large' | 'enterprise' | null;
  contactEmail: string | null;
  contactPhone: string | null;
  address: {
    street: string;
    city: string;
    state: string;
    country: string;
    postalCode: string;
  } | null;
  licenseType: 'individual' | 'team' | 'enterprise';
  maxUsers: number;
  billingEmail: string | null;
  accountOwnerId: string | null;
  stripeCustomerId: string | null;
  stripeProductId: string | null;
  status: 'trial' | 'active' | 'suspended' | 'cancelled';
  createdAt: Date;
  updatedAt: Date;
};

export type OrganizationsInsert = {
  id?: string;
  name: string;
  slug: string;
  description?: string | null;
  website?: string | null;
  logoUrl?: string | null;
  organizationType:
    | 'church'
    | 'denomination'
    | 'seminary'
    | 'ministry_network'
    | 'nonprofit'
    | 'business'
    | 'other';
  sizeCategory?: 'startup' | 'small' | 'medium' | 'large' | 'enterprise' | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  address?: {
    street: string;
    city: string;
    state: string;
    country: string;
    postalCode: string;
  } | null;
  licenseType?: 'individual' | 'team' | 'enterprise';
  maxUsers?: number;
  billingEmail?: string | null;
  accountOwnerId?: string | null;
  stripeCustomerId?: string | null;
  stripeProductId?: string | null;
  status?: 'trial' | 'active' | 'suspended' | 'cancelled';
  createdAt?: Date;
  updatedAt?: Date;
};

export type OrganizationsUpdate = Partial<OrganizationsInsert>;

// OrganizationMemberships types from auth.ts
export type OrganizationMembershipsSelect = {
  id: string;
  userId: string;
  organizationId: string;
  role: 'owner' | 'admin' | 'member' | 'viewer';
  permissions: string[];
  status: 'pending' | 'active' | 'inactive' | 'cancelled';
  joinedAt: Date | null;
  invitedAt: Date | null;
  invitedBy: string | null;
  createdAt: Date;
  updatedAt: Date;
};

export type OrganizationMembershipsInsert = {
  id?: string;
  userId: string;
  organizationId: string;
  role: 'owner' | 'admin' | 'member' | 'viewer';
  permissions?: string[];
  status?: 'pending' | 'active' | 'inactive' | 'cancelled';
  joinedAt?: Date | null;
  invitedAt?: Date | null;
  invitedBy?: string | null;
  createdAt?: Date;
  updatedAt?: Date;
};

export type OrganizationMembershipsUpdate =
  Partial<OrganizationMembershipsInsert>;
